# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fill in the missing picture
#' 
#' @param pic is the input matrix which needs to be full of
#' @param lambda is the penalty variable
#' @param ac is the bool variable, 1 means using accelerate method, 0 means no accelerate
#' @return the matrix which has already full of
#' @examples
#' require(recoverpic)
#' nimgac = recover(vimg,0.3)
recover <- function(pic, lambda, ac = 1L) {
    .Call('recoverpic_recover', PACKAGE = 'recoverpic', pic, lambda, ac)
}

#' Vague picture
#' 
#' @param pic is the input matrix needs to vague
#' @return the matrix which has already vagued
#' @examples
#' require(recoverpic)
#' vimg = vague(img)
vague <- function(pic) {
    .Call('recoverpic_vague', PACKAGE = 'recoverpic', pic)
}

