// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// recover
Rcpp::List recover(arma::mat& pic, double lambda, bool ac);
RcppExport SEXP recoverpic_recover(SEXP picSEXP, SEXP lambdaSEXP, SEXP acSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pic(picSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< bool >::type ac(acSEXP);
    rcpp_result_gen = Rcpp::wrap(recover(pic, lambda, ac));
    return rcpp_result_gen;
END_RCPP
}
// vague
arma::mat vague(arma::mat pic);
RcppExport SEXP recoverpic_vague(SEXP picSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type pic(picSEXP);
    rcpp_result_gen = Rcpp::wrap(vague(pic));
    return rcpp_result_gen;
END_RCPP
}
